---
- name: deploy vm pve
  gather_facts: false
  remote_user: root
  #remote_user: ansible
  #become: yes
  #become_method: sudo
  hosts: pve
  vars_files:
    -  defaults/main.yml
    -  defaults/secrets.yml

  roles:
    - { role: ../pve_deploy_vm }
